create database ecosenac;

use ecosenac;

CREATE TABLE USUARIO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(40),
    EMAIL VARCHAR(30) UNIQUE,
    SENHA VARCHAR(20),
    TELEFONE VARCHAR(14)
);
